image: 'probo/ubuntu:latest'

environment:
  PYTHON_VERSION: '3.8'

steps:
  - name: Install Python and dependencies
    command: |
      sudo apt-get update
      sudo apt-get install -y python3 python3-pip gcc
      pip3 install telebot pymongo aiohttp
      
  - name: Compile C file
    command: |
      gcc soul.c -o soul -lpthread
      
  - name: Run Python script
    command: |
      python3 soul.py
      
